import { Uyeler } from './Uyeler';
import { Yapi } from './Yapi';
import { YapiTipi } from './Ytipi';
import { Yakit } from './Yakit';
import { Tapu } from './Tapu';
import { KDurumu } from './Kdurumu';
import { BKat } from './Kat';
import { Isinma } from './Isinma';
import { Il } from './Il';
import { Cephe } from './Cephe';
export class Evilanim{
    Ilanid :string;
    ilanbasligi :string;
    ilanaciklama :string;
    Fiyat :number;
    odasayi :number;
    salonsayi :number;
    banyosayi :number;
    brut:number;
    net :number;
    EvIsinmaid :number;
    EvIsinma :string;
    binayas :number;
    Katid :number;
    Katb:string;
    binakatsayi :number;
    konutsekil1 :string;
    esyali :string;
    EvYakid :number;
    EvYakit:string;
    EvYapid :number;
    EvYapidb:string;
    EvKDid :number;
    EvKDidb:string;
    aidat :number;
    takasmi :string;
    sitemi :string;
    EvCepheid :number;
    EvCepheidb:string;
    EvTapid :number;
    EvTapidb:string;
    kira :number;
    Evsehirid :number;
    Evsehiridb:string;
    ilcenere :string;
    mahnere :string;
    resim :string;
    satilikirami :string;
    EvYTid :number;
    EvYTidb:string;
    Evuid :string;
    Evuidb:string;
    kredi :string;
    goruntu :string;


    Cephebilgi:Cephe;
    Illerbilgi:Il;
    Isinmabilgi:Isinma;
    Katbilgi:BKat;
    Kullanimbilgi:KDurumu;
    Tapubilgi:Tapu;
    Yakitbilgi:Yakit;
    YTipibilgi:YapiTipi;
    Yapibilgi:Yapi;
    uyebilgi:Uyeler;
}