//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ilanlar()
        {
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public string Ilanid { get; set; }
        public string ilanbasligi { get; set; }
        public string ilanaciklama { get; set; }
        public decimal Fiyat { get; set; }
        public int odasayi { get; set; }
        public int salonsayi { get; set; }
        public int banyosayi { get; set; }
        public double brut { get; set; }
        public int net { get; set; }
        public int EvIsinmaid { get; set; }
        public int binayas { get; set; }
        public int Katid { get; set; }
        public int binakatsayi { get; set; }
        public string konutsekil1 { get; set; }
        public string esyali { get; set; }
        public int EvYakid { get; set; }
        public int EvYapid { get; set; }
        public int EvKDid { get; set; }
        public decimal aidat { get; set; }
        public string takasmi { get; set; }
        public string sitemi { get; set; }
        public int EvCepheid { get; set; }
        public int EvTapid { get; set; }
        public decimal kira { get; set; }
        public int Evsehirid { get; set; }
        public string ilcenere { get; set; }
        public string mahnere { get; set; }
        public string resim { get; set; }
        public string satilikirami { get; set; }
        public int EvYTid { get; set; }
        public string Evuid { get; set; }
        public string kredi { get; set; }
        public string goruntu { get; set; }
    
        public virtual Cephe Cephe { get; set; }
        public virtual Isinma Isinma { get; set; }
        public virtual Uyeler Uyeler { get; set; }
        public virtual Kat Kat { get; set; }
        public virtual Kullanim Kullanim { get; set; }
        public virtual Iller Iller { get; set; }
        public virtual Tapu Tapu { get; set; }
        public virtual Yakit Yakit { get; set; }
        public virtual Yapi Yapi { get; set; }
        public virtual YTipi YTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
